FROM ubuntu:16.04

MAINTAINER bwnyasse

ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get update && \
  apt-get install -y software-properties-common curl git htop man wget make python g++

CMD ["bash"]
