---
# tasks file for docker.ubuntu
- name: Fail if a release is < 16.04 ( Xenial Xerus) Ubuntu
  fail:
    msg: "{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role"
  when: ansible_distribution_version|version_compare(16.04, '<')
  register: goodrelease

- name: Install scribus
  apt: pkg=scribus state=installed update_cache=true
  when: goodrelease
