---
# tasks file for intellij
- name: Fail if not a new release of Ubuntu ( 16.04)
  fail:
    msg: "{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role"
  when: ansible_distribution_version|version_compare(16.04, '<')

- name: Add intellij-idea-community PPA Repository
  apt_repository: repo='{{ intellij.ppa }}' state=present
  register: ppastable

- name: Install intellij-idea-community
  apt: pkg=intellij-idea-community state=installed update_cache=true
  when: ppastable|success
