---
- name: Check if gitkraken is installed
  command: dpkg-query -W gitkraken
  register: gitkraken_check_deb
  failed_when: gitkraken_check_deb.rc > 1
  changed_when: gitkraken_check_deb.rc == 1

- name: Download gitkraken
  get_url:
    url="{{ gitkraken_url }}"
    dest="/home/{{ ansible_env.USER }}/tmp/{{ gitkraken_name }}.deb"
  when: gitkraken_check_deb.rc == 1

- name: Install gitkraken
  become: yes
  become_user: root
  apt: deb="/home/{{ ansible_env.USER }}/tmp/{{ gitkraken_name }}.deb"
  when: gitkraken_check_deb.rc == 1
