---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
    - Start Nginx

- name: Add Share log directory
  when: nginxinstalled|success
  file: dest=/usr/share/nginx/logs mode=775 state=directory

- name: Add H5BP Config
  when: nginxinstalled|success
  copy: src=h5bp dest=/etc/nginx owner=root group=root

  # Disable the default virtual host by removing the symlink to the default file from the sites-enabled directory
- name: Disable Default Site
  when: nginxinstalled|success
  file: dest=/etc/nginx/sites-enabled/default state=absent

  # Copy the serversforhackers.com.conf.j2 virtual host template into the Nginx configuration
- name: Add SFH Site Config
  when: nginxinstalled|success
  register: sfhconfig
  template: src=default.com.j2 dest=/etc/nginx/sites-available/{{ domain }}.conf owner=root group=root

  # Enable the virtual host configuration by symlinking it to the sites-enabled directory
- name: Enable SFH Site Config
  when: sfhconfig|success
  file: src=/etc/nginx/sites-available/{{ domain }}.conf dest=/etc/nginx/sites-enabled/{{ domain }}.conf state=link

  # Create the web root
- name: Create Web root
  when: nginxinstalled|success
  file: dest=/var/www/{{ domain }}/public mode=775 state=directory owner=www-data group=www-data
  notify:
    - Reload Nginx

 # Change permission for the project root directory, which is one level above the web root created previously
- name: Web Root Permissions
  when: nginxinstalled|success
  file: dest=/var/www/{{ domain }} mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - ReStart Nginx
