---
- name: Add Bash Aliases
  copy: src=.bash_aliases dest={{ ansible_env.HOME}}

- name: Add Bash Profiles
  copy: src=.bash_profiles dest={{ ansible_env.HOME}}

- name: Add Bashrc
  copy: src=.bashrc dest={{ ansible_env.HOME}}

- name: source bashrc
  shell: source {{ ansible_env.HOME}}/.bashrc
  args:
    executable: /bin/bash
