---
- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  
- name: Add Docker repository and update apt cache
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    mode: '644'
    update_cache: yes
    state: present



