---
- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: https://apt.dockerproject.org/gpg
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Alternative | Add Docker repository key
  shell: "curl -sSL https://apt.dockerproject.org/gpg | sudo apt-key add -"
  when: add_repository_key|failed

- name: Add Docker repository and update apt cache
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    mode: '644'
    update_cache: yes
    state: present



